//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertCenter.Models.DbModels
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// api Data Structure.
    /// </summary>
    [Serializable]
    public partial class api
    {
        /*代码自动生成工具自动生成 - 车毅*/

        /// <summary>
        /// 权限id
        /// </summary>
        public int apiid { get; set; }

        /// <summary>
        /// 应用类型
        /// </summary>
        public int apptype { get; set; }

        /// <summary>
        /// 应用级别
        /// </summary>
        public int appgradeno { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public int categoryid { get; set; }

        /// <summary>
        /// 接口名
        /// </summary>
        public string apiname { get; set; }

        /// <summary>
        /// 接口标题
        /// </summary>
        public string apititle { get; set; }

        /// <summary>
        /// area
        /// </summary>
        public string area { get; set; }

        /// <summary>
        /// controller
        /// </summary>
        public string controller { get; set; }

        /// <summary>
        /// action
        /// </summary>
        public string action { get; set; }

        /// <summary>
        /// para
        /// </summary>
        public string para { get; set; }

        /// <summary>
        /// api说明
        /// </summary>
        public string apidesc { get; set; }

        /// <summary>
        /// 是否冻结
        /// </summary>
        public int freeze { get; set; }
    }
}
