//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertCenter.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class app
    {
        public string appid { get; set; }
        public int apptype { get; set; }
        public int appgradeno { get; set; }
        public string appsecret { get; set; }
        public string appdesc { get; set; }
        public int freeze { get; set; }
        public string appname { get; set; }
    
        public virtual appgrade appgrade { get; set; }

    }
}
