//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertCenter.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class appgrade
    {
        public appgrade()
        {
            this.apps = new HashSet<app>();
           // this.gradepermissions = new HashSet<gradepermission>();
        }
    
        public int apptype { get; set; }
        public int appgradeno { get; set; }
        public string appgradename { get; set; }
        public string appgradedesc { get; set; }
    
        public virtual ICollection<app> apps { get; set; }
       // public virtual ICollection<gradepermission> gradepermissions { get; set; }
    }
}
