//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertCenter.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_token
    {
        public string id { get; set; }
        public string token { get; set; }
        public string userid { get; set; }
        public string username { get; set; }
        public string appid { get; set; }
        public System.DateTime createtime { get; set; }
        public System.DateTime expires { get; set; }
    }

    public enum TokenType
    {
        usertoken=0,
        shoptoken=1,
        managetoken=2
    }
}
